title: "Anisa Davis"
description: "Visual Artist & Game Developer"
theme: minima

header_pages:
  - about.md
  - projects.md
  - art.md
  - contact.md

# Tell Jekyll to load your custom CSS
sass:
  style: compressed

