# _config.yml

title: "Anisa Davis"
description: "Visual Artist & Game Developer"
theme: jekyll-theme-chirpy

# Navigation menu items — pages you’ll create
header_pages:
  - about.md
  - projects.md
  - art.md
  - contact.md

# Optional: show last updated date on posts/pages
show_last_updated_at: true
